# Generated by Django 5.2.3 on 2025-07-11 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='diunggah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
