# Generated by Django 5.2.3 on 2025-07-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_app', '0002_dokumen_diunggah_oleh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='jenis',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('surat_tugas', 'Surat Tugas'), ('data_pengawas_pengurus_dan_pegawai', 'Data Pengawas, Pengurus, dan Pegawai'), ('surat_ijin_/_cuti', 'Surat Ijin / Cuti'), ('call_memo', 'Call Memo'), ('nota_interm', 'Nota Interm'), ('pinjaman_anggota', 'Pinjaman Anggota'), ('nota_dinas', 'Nota Dinas'), ('jurnal_&_lampiran', 'Jurnal & Lampiran'), ('perjanjian_kerjasama', 'Perjanjian Kerjasama'), ('laporan_keuangan_koperasi_swadharma', 'Laporan Keuangan Koperasi Swadharma'), ('laporan_keuangan_perusahaan_anak', 'Laporan Keuangan Perusahaan Anak'), ('notulen_rapat', 'Notulen Rapat'), ('dokumen_RAT', 'Dokumen RAT'), ('bpp', 'BPP (Buku Peraturan Perusahaan)'), ('laporan_pajak', 'Laporan Pajak'), ('sk_pengurus', 'SK Pengurus')], max_length=50),
        ),
    ]
