# Generated by Django 5.2.3 on 2025-07-14 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_app', '0003_alter_dokumen_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('uploader', 'Uploader'), ('admin', 'Admin')], max_length=10, verbose_name='Level Akses'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unit_kerja',
            field=models.CharField(choices=[('UPP', 'UPP'), ('USD', 'USD'), ('UPA', 'UPA'), ('UKS', 'UKS'), ('UDP', 'UDP'), ('UPS', 'UPS'), ('UPI', 'UPI'), ('UAP', 'UAP')], max_length=3, verbose_name='Unit Kerja'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='bulan',
            field=models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=10, verbose_name='Bulan'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Upload'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='diunggah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diunggah Oleh'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file_scan',
            field=models.FileField(blank=True, null=True, upload_to='scan/', verbose_name='File Scan'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='jenis',
            field=models.CharField(choices=[('surat_masuk', 'Surat Masuk'), ('surat_keluar', 'Surat Keluar'), ('surat_tugas', 'Surat Tugas'), ('data_pengawas_pengurus_dan_pegawai', 'Data Pengawas, Pengurus, dan Pegawai'), ('surat_ijin_/_cuti', 'Surat Ijin / Cuti'), ('call_memo', 'Call Memo'), ('nota_interm', 'Nota Interm'), ('pinjaman_anggota', 'Pinjaman Anggota'), ('nota_dinas', 'Nota Dinas'), ('jurnal_&_lampiran', 'Jurnal & Lampiran'), ('perjanjian_kerjasama', 'Perjanjian Kerjasama'), ('laporan_keuangan_koperasi_swadharma', 'Laporan Keuangan Koperasi Swadharma'), ('laporan_keuangan_perusahaan_anak', 'Laporan Keuangan Perusahaan Anak'), ('notulen_rapat', 'Notulen Rapat'), ('dokumen_RAT', 'Dokumen RAT'), ('bpp', 'BPP (Buku Peraturan Perusahaan)'), ('laporan_pajak', 'Laporan Pajak'), ('sk_pengurus', 'SK Pengurus')], max_length=50, verbose_name='Jenis Dokumen'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='kardus',
            field=models.CharField(max_length=50, verbose_name='Kardus'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='nama_file',
            field=models.CharField(max_length=255, verbose_name='Nama File'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='nomor',
            field=models.CharField(max_length=50, verbose_name='Nomor'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='rak',
            field=models.CharField(max_length=50, verbose_name='Rak'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='status',
            field=models.CharField(default='belum_verifikasi', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='tahun',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='unit',
            field=models.CharField(choices=[('UPP', 'UPP'), ('USD', 'USD'), ('UPA', 'UPA'), ('UKS', 'UKS'), ('UDP', 'UDP'), ('UPS', 'UPS'), ('UPI', 'UPI'), ('UAP', 'UAP')], max_length=3, verbose_name='Unit'),
        ),
    ]
