# Generated by Django 5.2.3 on 2025-07-14 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_app', '0004_alter_customuser_level_alter_customuser_unit_kerja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='tanggal_upload',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tanggal Upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokumen',
            name='waktu_upload',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Waktu Upload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal & Waktu Upload'),
        ),
    ]
