# Generated by Django 5.2.3 on 2025-07-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_app', '0005_dokumen_tanggal_upload_dokumen_waktu_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='id',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='arsip_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Arsip'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='nomor_berkas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomor Berkas'),
        ),
    ]
