# Generated by Django 5.2.3 on 2025-07-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_app', '0006_remove_dokumen_id_dokumen_arsip_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='nomor_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='status',
            field=models.CharField(choices=[('belum verifikasi', 'Belum Verifikasi'), ('sudah verifikasi', 'Sudah Verifikasi')], default='belum verifikasi', max_length=20, verbose_name='Status'),
        ),
    ]
